### ISSUE TITLE
useNetworkStatus

### ISSUE THREAD

**Issue by jamiebuilds** [rehooks/ideas#1]
- https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API
- https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation

```js
useNetworkStatus();
// interface NetworkInformation
```

**Comment by iamsolankiamit** [comment]
https://github.com/iamsolankiamit/online-offline

**Comment by mathdroid** [comment]
https://github.com/mathdroid/online-status

**Comment by iamsolankiamit** [comment]
https://github.com/rehooks/network-status
