### ISSUE TITLE
useLocalState

### ISSUE THREAD

**Issue by EmilTholin** [rehooks/ideas#10]
It would be neat with a hook named something like `useLocalState`/`useLocalStorage` that syncs the data from/to localStorage.

**Comment by iamsolankiamit** [comment]
Cool, working on it.

**Comment by iamsolankiamit** [comment]
https://github.com/rehooks/local-storage

**Comment by harrysolovay** [comment]
I made a library that does this a bit differently. Check it out [here](https://github.com/harrysolovay/persistence-hooks). It isn't yet up on NPM but will be soon.
