### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by prichodko** [rehooks/ideas#16]
My friend & designer - [@jakubnespor](https://twitter.com/jakubnespor) ([dribbble](https://dribbble.com/jakubnespor)) was sitting next to me when I was watching React Conf. Although he is not from React world, I got him hooked too. 😂 

## Proposal
![rehooks-logo](https://user-images.githubusercontent.com/14926950/47535015-665a5b80-d86e-11e8-8d4c-da117b48642d.png)

**Comment by jamiebuilds** [comment]
@jakubnespor Would it be okay to license this logo as Creative Commons so that it can be used in the open source project?

**Comment by fouad** [comment]
:fire: 

my only comment: do we want to play with some colors with it? would avoid the react logo color, but a blue or pink could look nice

**Comment by jakubnespor** [comment]
@jamiebuilds sure, of course ✌️

**Comment by jakubnespor** [comment]
@fouad I explored few more colors, but I like black the most... it's scalable, works everywhere the same, but I am totally open to more options 😊
@jamiebuilds btw if you'd need more formats of the logo, I can send them over 💪

**Comment by jamiebuilds** [comment]
Yeah, could you send me:

- A vector version of the logo + text (`.ai`, `.sketch`, `.svg`, etc)
- PNGs with transparent backgrounds of:
  - logo + text
  - logo

**Comment by fouad** [comment]
Sg! it’s also the cleanest starting point, thanks for taking a look @jakubnespor

:ship:

**Comment by jakubnespor** [comment]
@jamiebuilds Here you go: 
[rehooks-logo-pack.zip](https://github.com/rehooks/ideas/files/2517191/rehooks-logo-pack.zip)

**Comment by robwierzbowski** [comment]
This logo is pure quality

**Comment by jamesplease** [comment]
Nice work here @jakubnespor :v:

**Comment by jamiebuilds** [comment]
Put everything here https://github.com/rehooks/logo

Thanks again @jakubnespor !
