### ISSUE TITLE
useSocket

### ISSUE THREAD

**Issue by juancuiule** [rehooks/ideas#22]
I'll be working on this in this repo https://github.com/juancuiule/socket
using socket.io to emit/receive events

**Comment by ezekielchentnik** [comment]
why not regular websocket api?  example:

In app entry
```
const ws = new WebSocket('ws://localhost:8080');

render(
  <Provider value={[ws]}>
    <App />
  </Provider>,
  root
);

```
In a component
```
function Messages() {
  const [ws] = useContext(Context);
  const [message, send] = useWebSocket(ws, ['message']);
  return (
    <div>{message}</div>
  );
}

```

**Comment by juancuiule** [comment]
I said socket.io because I have worked with it in the past, but I think that you are right, I'll do it with the regular api

**Comment by juancuiule** [comment]
Here is the first version of this `useWebSocket` hook in https://github.com/juancuiule/socket

**Comment by juancuiule** [comment]
@jamiebuilds
