### ISSUE TITLE
persistence hooks

### ISSUE THREAD

**Issue by harrysolovay** [rehooks/ideas#42]
## UPDATE

[Here is a beta](https://github.com/harrysolovay/persistence-hooks) of this library

<hr />

## ORIGINAL

I'm currently working on `usePersistentState` which behaves similarly to the `useState` hook, but stores the data according to a specified persistence strategy:

## Available strategies:
**(on web)** localStorage, sessionStorage and cookies
**(in React Native**) AsyncStorage and SecureStore

## API usage:

```jsx
import usePersistentState from 'use-persistent-state'

const Counter = () => {
  const [count, setCount] = usePersistentState(0, {
    strategy: window.localStorage,
    key: 'counter',
  })
  return <>
    count: {count}
    <button
      onClick={() => setCount(count => count + 1)}
      children='increment'
    />
    <button
      onClick={() => setCount(count => count - 1)}
      children='decrement'
    />
  </>
}
```

**Comment by harrysolovay** [comment]
Just pushed [a first version](https://github.com/harrysolovay/persistence-hooks)

I didn't yet publish it to NPM. My thinking is that hopefully this package can exist in the official rehooks domain? Having this repo owned by rehooks would make it more visible (I'll absolutely maintain and improve it).

Please let me know how to proceed.

Kind regards,

Harry

**Comment by j-f1** [comment]
How about naming them `use*State` (e.g. `useCookieState(key, initial)`) instead of `useStateAnd*` Or how about `use*(useState(...))` (e.g. `useCookie(key, [value, setValue])`)? 🚲🏠

**Comment by harrysolovay** [comment]
@j-f1 I would love to simplify, but I think `useCookieState` isn't explicit enough (the "And" makes clear that it's synchronizing both). Piping `use*(useState(...))` would be more modular (incase we want something like `useCookie` that doesn't touch state)... I like the train of thought... something like recompose for hooks would be really fun to work on. Please let me know if you have any more ideas for this lib. Thx 👍
