### ISSUE TITLE
useComponentSize

### ISSUE THREAD

**Issue by fouad** [rehooks/ideas#6]
@jamiebuilds https://github.com/fouad/component-size want to add me to org then I'll transfer?

**Comment by jamiebuilds** [comment]
Sure!

**Comment by fouad** [comment]
great! anyone reading in the future can find at https://github.com/rehooks/component-size

**Comment by mohammedzamakhan** [comment]
Why can't I create a issue on the component-size repo?

**Comment by fouad** [comment]
@mohammedzamakhan not sure what happened there, just turned it on! https://github.com/rehooks/component-size/issues
