### ISSUE TITLE
useScroll

### ISSUE THREAD

**Issue by prichodko** [rehooks/ideas#7]
https://developer.mozilla.org/en-US/docs/Web/Events/scroll

```js
let scroll = useScroll(300) // specify throttle
console.log(scroll) // x, y
```

**Comment by jamiebuilds** [comment]
Probably better to have one that is `useWindowScrollPosition()` which returns `{ x, y }` with a value that updates on the window scroll event.

**Comment by jamiebuilds** [comment]
Alternatively, you could have `useElementScrollPosition(ref)`

**Comment by prichodko** [comment]
I agree with the name being more explicit.

**Comment by prichodko** [comment]
Let's do it?

**Comment by jamiebuilds** [comment]
Go for it

**Comment by prichodko** [comment]
@jamiebuilds  https://github.com/prichodko/window-scroll-position

I also added support for throttling via [lodash.throttle](https://www.npmjs.com/package/lodash.throttle) and detecting of passive option using [this](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

**Comment by prichodko** [comment]
Let me know, if there is anything missing to get this to @rehooks.

**Comment by jamiebuilds** [comment]
You wanna transfer it to the rehooks org? You have access now

**Comment by prichodko** [comment]
Done - https://github.com/rehooks/window-scroll-position
